# permissions for end users to view esclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: escluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: elasticsearch-operator
    app.kubernetes.io/part-of: elasticsearch-operator
    app.kubernetes.io/managed-by: kustomize
  name: escluster-viewer-role
rules:
- apiGroups:
  - es.yasyx.cn
  resources:
  - esclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - es.yasyx.cn
  resources:
  - esclusters/status
  verbs:
  - get
